### YamlMime:ManagedReference
items:
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  id: ForeignKeyReferenceAlreadyHasValueException
  children:
  - System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor
  - System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String)
  - System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException
  nameWithType: ForeignKeyReferenceAlreadyHasValueException
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  type: Class
  summary: "Representa os erros que adotar quando é efetuada uma tentativa de alterar uma chave externa quando a entidade já está carregada."
  syntax:
    content: 'public class ForeignKeyReferenceAlreadyHasValueException : InvalidOperationException'
  inheritance:
  - System.InvalidOperationException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor
  id: '#ctor'
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException()
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException&quot;> </xref> classe com uma mensagem fornecido pelo sistema que descreve o erro."
  remarks: "Este construtor inicializa a <xref:System.Exception.Message%2A>propriedade da instância do novo a uma mensagem fornecido pelo sistema que descreve o erro, como &quot;DefaultMessageDisplayedByParameterlessCtorWriterMustSupply&quot;.</xref:System.Exception.Message%2A> Esta mensagem tem em consideração o idioma atual do sistema.       A tabela seguinte mostra os valores de propriedade inicial para uma instância do <xref:System.InsufficientMemoryException>.</xref:System.InsufficientMemoryException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| A cadeia de mensagem de erro localizado. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ForeignKeyReferenceAlreadyHasValueException ();
    parameters: []
  overload: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException(String)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException&quot;> </xref> classe com uma mensagem especificada que descreve o erro."
  remarks: "A tabela seguinte mostra os valores de propriedade inicial para uma instância do <xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>.</xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| A cadeia de mensagem de erro especificada no `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ForeignKeyReferenceAlreadyHasValueException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A mensagem que descreve a exceção. O autor da chamada deste construtor não é necessária para se certificar de que esta cadeia tem foram localizada da cultura atual do sistema."
  overload: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Inicializa uma nova instância do <xref href=&quot;System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException&quot;> </xref> classe com uma mensagem de erro especificado e uma referência a exceção interna que é a causa desta exceção."
  remarks: "Uma exceção que é acionada como um resultado direto de uma exceção anterior deve incluir uma referência a exceção anterior no <xref:System.Exception.InnerException%2A>propriedade.</xref:System.Exception.InnerException%2A> O <xref:System.Exception.InnerException%2A>propriedade devolve o mesmo valor que é transmitido para o construtor ou `null` se o <xref:System.Exception.InnerException%2A>propriedade não fornecer o valor da exceção interna para o construtor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       A tabela seguinte mostra os valores de propriedade inicial para uma instância do <xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>.</xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| A cadeia de mensagem de erro especificada no `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ForeignKeyReferenceAlreadyHasValueException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A mensagem que descreve a exceção. O autor da chamada deste construtor não é necessária para se certificar de que esta cadeia tem foram localizada da cultura atual do sistema."
    - id: innerException
      type: System.Exception
      description: "A exceção é a causa da exceção atual. Se o `innerException` não é o parâmetro <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, a exceção atual num <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> bloco que processa a exceção interna."
  overload: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.InvalidOperationException
  isExternal: false
  name: System.InvalidOperationException
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException()
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String)
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException(String)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String,System.Exception)
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException
